sudo: required

addons:
  chrome: stable

services:
  - docker

before_install:
  - docker build -t xonefobic/playing-with-docker-and-ci-cd -f Dockerfile.dev .

script:
  - docker run xonefobic/playing-with-docker-and-ci-cd yarn test --no-watch --no-progress --browsers=ChromeHeadless
